# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a15tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Control_Unit/Control_Unit.cache/wt [current_project]
set_property parent.project_path D:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Control_Unit/Control_Unit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Control_Unit/Control_Unit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Documents/GitHub/EECS_542_SeniorDesignProject/VHDL Files/Basic_Gates.vhd}
  {D:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Control_Unit/Control_Unit.srcs/sources_1/imports/VHDL Entities/Clock_Divider.vhd}
  {D:/Documents/GitHub/EECS_542_SeniorDesignProject/VHDL Files/Multiplexers.vhd}
  {D:/Documents/GitHub/EECS_542_SeniorDesignProject/VHDL Files/EECS_542_Clock_Block.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top EECS_542_Clock_Block -part xc7a15tftg256-1


write_checkpoint -force -noxdef EECS_542_Clock_Block.dcp

catch { report_utilization -file EECS_542_Clock_Block_utilization_synth.rpt -pb EECS_542_Clock_Block_utilization_synth.pb }
