# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo.xci
# IP: The module: 'bram_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo/bram_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo/bram_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo.xci
# IP: The module: 'bram_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo/bram_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Documents/GitHub/EECS_542_SeniorDesignProject/Vivado_Projects/Senior_Design_For_OK/Senior_Design_For_OK.srcs/sources_1/ip/bram_fifo_2/bram_fifo/bram_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
